-- experimental xlua decompilation support enabled, you are on your own!
local __rt_1 = {1}
local __rt_2 = {2}
local __rt_3 = {3}
local __rt_4 = {4}
local __rt_5 = {6}
local __rt_6 = {5, 2}
local __rt_7 = {5}
local __rt_8 = {7}
local __rt_9 = {8, 2}
local __rt_10 = {}
local activity_lobby_interact_obj = {
  [24001] = {
    {
      act_id = 24001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_1,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 1,
      obj_path = "InteractObjs/inlet_3",
      obj_type = 0
    },
    {
      act_id = 24001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_2,
      obj_fx_path = "inlet_2_fx",
      obj_hide = false,
      obj_id = 2,
      obj_path = "InteractObjs/inlet_2",
      obj_type = 0
    },
    {
      act_id = 24001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_3,
      obj_fx_path = "inlet_4_fx",
      obj_hide = false,
      obj_id = 3,
      obj_path = "InteractObjs/inlet_4",
      obj_type = 0
    },
    {
      act_id = 24001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_4,
      obj_fx_path = "inlet_1_fx",
      obj_hide = false,
      obj_id = 4,
      obj_path = "InteractObjs/inlet_1",
      obj_type = 0
    },
    {
      act_id = 24001,
      hero_id = 0,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_5,
      obj_fx_path = "inlet_5_fx",
      obj_hide = false,
      obj_id = 5,
      obj_path = "InteractObjs/inlet_5",
      obj_type = 0
    },
    [11] = {
      act_id = 24001,
      hero_id = 1062,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_6,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 11,
      obj_path = "InteractObjs/dmodel_jiangyu",
      obj_type = 1
    },
    [12] = {
      act_id = 24001,
      hero_id = 1018,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_6,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 12,
      obj_path = "InteractObjs/dmodel_florence_newyear",
      obj_type = 1
    },
    [13] = {
      act_id = 24001,
      hero_id = 1044,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_6,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 13,
      obj_path = "InteractObjs/dmodel_kuro_newyear",
      obj_type = 1
    },
    [14] = {
      act_id = 24001,
      hero_id = 1022,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_6,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 14,
      obj_path = "InteractObjs/dmodel_aki_newyear",
      obj_type = 1
    },
    [15] = {
      act_id = 24001,
      hero_id = 1038,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_6,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 15,
      obj_path = "InteractObjs/dmodel_sakuya_newyear",
      obj_type = 1
    },
    [16] = {
      act_id = 24001,
      hero_id = 1005,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_6,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 16,
      obj_path = "InteractObjs/dmodel_croque_newyear",
      obj_type = 1
    }
  },
  [24003] = {
    {
      act_id = 24003,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_1,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 1,
      obj_path = "2023Festival_Entrance",
      obj_type = 0
    },
    {
      act_id = 24003,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_2,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 2,
      obj_path = "2023Festival_PrincipalLine",
      obj_type = 0
    },
    {
      act_id = 24003,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_3,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 3,
      obj_path = "2023Festival_Protoss",
      obj_type = 0
    },
    {
      act_id = 24003,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_4,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 4,
      obj_path = "2023Festival_Difficult",
      obj_type = 0
    },
    {
      act_id = 24003,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_7,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 5,
      obj_path = "2023Festival_Game_01",
      obj_type = 0
    },
    {
      act_id = 24003,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_5,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 6,
      obj_path = "2023Festival_nanaka_1",
      obj_type = 1
    },
    {
      act_id = 24003,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = false,
      obj_func = __rt_8,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 7,
      obj_path = "2023Festival_Countdown",
      obj_type = 0
    },
    [11] = {
      act_id = 24003,
      hero_id = 1058,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_9,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 11,
      obj_path = "model_hk416_idol",
      obj_type = 1
    },
    [12] = {
      act_id = 24003,
      hero_id = 1028,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_9,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 12,
      obj_path = "model_vee_idol",
      obj_type = 1
    },
    [13] = {
      act_id = 24003,
      hero_id = 1039,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_9,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 13,
      obj_path = "model_centaureissi_idol",
      obj_type = 1
    },
    [14] = {
      act_id = 24003,
      hero_id = 1061,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_9,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 14,
      obj_path = "model_undline_idol",
      obj_type = 1
    },
    [15] = {
      act_id = 24003,
      hero_id = 0,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_10,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 15,
      obj_path = "2023Festival_nanaka_2",
      obj_type = 1
    }
  },
  [25001] = {
    {
      act_id = 25001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_1,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 1,
      obj_path = "InteractObjs/inlet_4",
      obj_type = 0
    },
    {
      act_id = 25001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_2,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 2,
      obj_path = "InteractObjs/model_haze",
      obj_type = 1
    },
    {
      act_id = 25001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_3,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 3,
      obj_path = "InteractObjs/model_anna",
      obj_type = 1
    },
    {
      act_id = 25001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_4,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 4,
      obj_path = "InteractObjs/model_horizon",
      obj_type = 1
    },
    {
      act_id = 25001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = false,
      obj_func = __rt_7,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 5,
      obj_path = "InteractObjs/inlet_2",
      obj_type = 0
    },
    {
      act_id = 25001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_5,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 6,
      obj_path = "InteractObjs/inlet_3",
      obj_type = 0
    },
    {
      act_id = 25001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_8,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 7,
      obj_path = "InteractObjs/model_lind",
      obj_type = 1
    },
    {
      act_id = 25001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = false,
      obj_func = {8},
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 8,
      obj_path = "InteractObjs/inlet_1",
      obj_type = 0
    },
    {
      act_id = 25001,
      hero_id = 0,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_10,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 9,
      obj_path = "InteractObjs/model_sol",
      obj_type = 1
    },
    {
      act_id = 25001,
      hero_id = 0,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_10,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 10,
      obj_path = "model_magnhilda",
      obj_type = 1
    },
    {
      act_id = 25001,
      hero_id = 0,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_10,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 11,
      obj_path = "model_florence",
      obj_type = 1
    },
    {
      act_id = 25001,
      hero_id = 0,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_10,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 12,
      obj_path = "model_simo",
      obj_type = 1
    },
    {
      act_id = 25001,
      hero_id = 0,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_10,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 13,
      obj_path = "InteractObjs/model_sol_die",
      obj_type = 0
    }
  },
  [31001] = {
    {
      act_id = 31001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_1,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 1,
      obj_path = "InteractObjs/inlet_4",
      obj_type = 0
    },
    {
      act_id = 31001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_2,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 2,
      obj_path = "InteractObjs/inlet_3",
      obj_type = 0
    },
    {
      act_id = 31001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_3,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 3,
      obj_path = "InteractObjs/inlet_6",
      obj_type = 0
    },
    {
      act_id = 31001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_8,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 4,
      obj_path = "InteractObjs/inlet_5",
      obj_type = 0
    },
    {
      act_id = 31001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = false,
      obj_func = __rt_7,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 5,
      obj_path = "InteractObjs/inlet_2",
      obj_type = 0
    },
    {
      act_id = 31001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = false,
      obj_func = __rt_5,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 6,
      obj_path = "InteractObjs/inlet_1",
      obj_type = 0
    },
    {
      act_id = 31001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_4,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 7,
      obj_path = "InteractObjs/inlet_7",
      obj_type = 0
    }
  },
  [33001] = {
    {
      act_id = 33001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_1,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 1,
      obj_path = "Entropy_inlet_6",
      obj_type = 0
    },
    {
      act_id = 33001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_2,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 2,
      obj_path = "Entropy_inlet_5",
      obj_type = 1
    },
    {
      act_id = 33001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_3,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 3,
      obj_path = "Entropy_inlet_4",
      obj_type = 1
    },
    {
      act_id = 33001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = false,
      obj_func = __rt_4,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 4,
      obj_path = "Entropy_inlet_2",
      obj_type = 0
    },
    {
      act_id = 33001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_7,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 5,
      obj_path = "Entropy_inlet_3",
      obj_type = 0
    },
    {
      act_id = 33001,
      hero_id = 0,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_10,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 6,
      obj_path = "Entropy_decorate_1",
      obj_type = 1
    },
    {
      act_id = 33001,
      hero_id = 0,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_10,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 7,
      obj_path = "Entropy_decorate_2",
      obj_type = 1
    },
    {
      act_id = 33001,
      hero_id = 0,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_10,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 8,
      obj_path = "Entropy_inlet_5-die",
      obj_type = 1
    }
  },
  [33003] = {
    {
      act_id = 33003,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = false,
      obj_func = __rt_1,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 1,
      obj_path = "2023Aether_ billboard",
      obj_type = 0
    },
    {
      act_id = 33003,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_3,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 2,
      obj_path = "Aether_inlet_5",
      obj_type = 1
    },
    {
      act_id = 33003,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_4,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 3,
      obj_path = "Aether_inlet_6",
      obj_type = 1
    },
    {
      act_id = 33003,
      hero_id = 0,
      hide_head_ui = true,
      is_quick = true,
      obj_func = __rt_2,
      obj_fx_path = "",
      obj_hide = true,
      obj_id = 4,
      obj_path = "inlet_5",
      obj_type = 0
    },
    {
      act_id = 33003,
      hero_id = 0,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_2,
      obj_fx_path = "",
      obj_hide = true,
      obj_id = 5,
      obj_path = "inlet_1",
      obj_type = 0
    },
    {
      act_id = 33003,
      hero_id = 0,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_2,
      obj_fx_path = "",
      obj_hide = true,
      obj_id = 6,
      obj_path = "inlet_2",
      obj_type = 0
    },
    {
      act_id = 33003,
      hero_id = 0,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_2,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 7,
      obj_path = "inlet_3",
      obj_type = 0
    },
    {
      act_id = 33003,
      hero_id = 0,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_10,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 8,
      obj_path = "Aether_inlet_5_die",
      obj_type = 1
    },
    {
      act_id = 33003,
      hero_id = 0,
      hide_head_ui = true,
      is_quick = false,
      obj_func = __rt_10,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 9,
      obj_path = "Aether_inlet_6_die",
      obj_type = 1
    }
  },
  [40001] = {
    {
      act_id = 40001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = false,
      obj_func = __rt_1,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 1,
      obj_path = "2023Aether_ billboard",
      obj_type = 0
    },
    {
      act_id = 40001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_2,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 2,
      obj_path = "model_fresnel",
      obj_type = 1
    },
    {
      act_id = 40001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_3,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 3,
      obj_path = "inlet_2",
      obj_type = 0
    },
    {
      act_id = 40001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_4,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 4,
      obj_path = "model_anna",
      obj_type = 1
    },
    {
      act_id = 40001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_7,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 5,
      obj_path = "model_hubble_darkstar",
      obj_type = 1
    },
    {
      act_id = 40001,
      hero_id = 0,
      hide_head_ui = false,
      is_quick = true,
      obj_func = __rt_5,
      obj_fx_path = "",
      obj_hide = false,
      obj_id = 6,
      obj_path = "inlet_1",
      obj_type = 0
    }
  }
}
return activity_lobby_interact_obj
